spring:
  application:
    name: template-engine

server:
  port: 8080

logging:
  level:
    com.report.engine: INFO
    org.apache.poi: WARN

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    showCommonExtensions: true